const key = (import.meta.env.VITE_FESTIVAL ?? 'arabic') as 'arabic' | 'global';

const configs = {
  arabic: {
    taglineAr: 'أرشيف نقدي وتوثيقي شامل للمهرجان العربي عبر السنوات',
    taglineEn: 'A comprehensive critical and documentary archive of the Arab Festival through the years',
    titleAr: 'المهرجان العربي',
    titleEn: 'Arab Festival',
    subtitleAr: 'المعهد العالي للفنون المسرحية',
    subtitleEn: 'Higher Institute of Theatrical Arts',
    contactEmail: 'info@play-cast.com',
    logo: '🎭',
    apiPrefix: import.meta.env.VITE_API_PREFIX ?? '/hita_arab_festival',
    addressAr: 'المعهد العالي للفنون المسرحية\nأكاديمية الفنون\nمصر',
    addressEn: 'Higher Institute of Theatrical Arts\nAcademy of Arts\nEgypt',
    celebrationAr: 'انضم إلينا في الاحتفال بالمسرح العربي',
    celebrationEn: 'Join us in celebrating Arab theatre',
    aboutWhatIsTitleAr: 'ما هو المهرجان العربي؟',
    aboutWhatIsTitleEn: 'What is the Arab Festival?',
    aboutWhatIsTextAr: 'المهرجان العربي للمسرح هو حدث سنوي يستضيفه المعهد العالي للفنون المسرحية.',
    aboutWhatIsTextEn: 'The Arab Theatre Festival is an annual event hosted by the Higher Institute of Theatrical Arts.',
    aboutWhyArchiveTitleAr: 'لماذا هذا الأرشيف؟',
    aboutWhyArchiveTitleEn: 'Why This Archive?',
    aboutWhyArchiveTextAr: 'يهدف هذا الموقع إلى توثيق تاريخ المهرجان بشكل شامل، وحفظ النقد المسرحي المصاحب للعروض، وتوفير مرجع بحثي للباحثين والمهتمين بالمسرح العربي المعاصر.',
    aboutWhyArchiveTextEn: 'This website aims to comprehensively document the festival\'s history, preserve the theatrical criticism accompanying the performances, and provide a research reference for scholars and those interested in contemporary Arab theatre.',
  },
  global: {
    taglineAr: 'أرشيف نقدي وتوثيقي شامل للمهرجان العالمي عبر السنوات',
    taglineEn: 'A comprehensive critical and documentary archive of the World Theatre Festival through the years',
    titleAr: 'مهرجان المسرح العالمي',
    titleEn: 'World Theatre Festival',
    subtitleAr: 'المعهد العالي للفنون المسرحية',
    subtitleEn: 'Higher Institute of Theatrical Arts',
    contactEmail: 'info@play-cast.com',
    logo: '🌍',
    apiPrefix: import.meta.env.VITE_API_PREFIX ?? '/global_festival',
    addressAr: 'المعهد العالي للفنون المسرحية\nأكاديمية الفنون\nمصر',
    addressEn: 'Higher Institute of Theatrical Arts\nAcademy of Arts\nEgypt',
    celebrationAr: 'انضم إلينا في الاحتفال بمهرجان المسرح العالمي',
    celebrationEn: 'Join us in celebrating World Theatre',
    aboutWhatIsTitleAr: 'ما هو مهرجان المسرح العالمي؟',
    aboutWhatIsTitleEn: 'What is the World Theatre Festival?',
    aboutWhatIsTextAr: 'مهرجان المسرح العالمي هو حدث سنوي دولي يستضيفه المعهد العالي للفنون المسرحية، يجمع فرقاً مسرحية من مختلف أنحاء العالم.',
    aboutWhatIsTextEn: 'The World Theatre Festival is an annual international event hosted by the Higher Institute of Theatrical Arts, bringing together theatre companies from around the world.',
    aboutWhyArchiveTitleAr: 'لماذا هذا الأرشيف؟',
    aboutWhyArchiveTitleEn: 'Why This Archive?',
    aboutWhyArchiveTextAr: 'يهدف هذا الموقع إلى توثيق تاريخ المهرجان العالمي بشكل شامل، وحفظ النقد المسرحي المصاحب للعروض، وتوفير مرجع بحثي للباحثين والمهتمين بالمسرح العالمي المعاصر.',
    aboutWhyArchiveTextEn: 'This website aims to comprehensively document the World Theatre Festival\'s history, preserve the theatrical criticism accompanying the performances, and provide a research reference for scholars and those interested in contemporary world theatre.',
  },
} as const;

export const festivalConfig = configs[key];
